import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { AdminLayout } from "@/admin/AdminLayout";

interface Summary { registered_users: number; active_users: number; active_subscribers: number; standard_subscribers: number; pro_subscribers: number; premium_subscribers: number; creator_subscribers: number; generation_requests_today: number; videos_today: number; images_today: number; total_revenue: number; revenue_today: number; }

export function AdminOperationsPage() {
  const [summary, setSummary] = useState<Summary | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; void (async () => { const { data, error: queryError } = await supabase.from("v_admin_operations_summary").select("*").single(); if (!active) return; if (queryError) setError(queryError.message); else setSummary(data as Summary); })(); return () => { active = false; }; }, []);
  const cards = summary ? [["Registered users", summary.registered_users], ["Active users", summary.active_users], ["Active subscribers", summary.active_subscribers], ["Requests today", summary.generation_requests_today], ["Videos today", summary.videos_today], ["Images today", summary.images_today]] : [];
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold text-ink-900">Operations & Margin</h1><p className="mt-1 text-sm text-ink-500">Live operational metrics from the protected database summary.</p></div>{error && <div className="card p-4 text-sm text-rose-600">Unable to load operations summary: {error}</div>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([label, value]) => <div key={String(label)} className="card p-5"><p className="text-sm text-ink-500">{label}</p><p className="mt-2 text-2xl font-semibold text-ink-900">{Number(value).toLocaleString()}</p></div>)}</div>{summary && <div className="grid gap-4 lg:grid-cols-2"><section className="card p-5"><h2 className="font-semibold">Subscribers by plan</h2><div className="mt-4 space-y-3">{[["Standard",summary.standard_subscribers],["Pro",summary.pro_subscribers],["Premium",summary.premium_subscribers],["Creator",summary.creator_subscribers]].map(([name,count]) => <div key={String(name)} className="flex justify-between text-sm"><span>{name}</span><strong>{Number(count).toLocaleString()}</strong></div>)}</div></section><section className="card p-5"><h2 className="font-semibold">Revenue</h2><div className="mt-4 grid grid-cols-2 gap-4"><div><p className="text-xs text-ink-500">All-time successful</p><p className="mt-1 text-xl font-semibold">${Number(summary.total_revenue).toLocaleString()}</p></div><div><p className="text-xs text-ink-500">Today</p><p className="mt-1 text-xl font-semibold">${Number(summary.revenue_today).toLocaleString()}</p></div></div><p className="mt-4 text-xs text-ink-500">Provider cost and gross margin will only be shown once verified provider-cost events are recorded; no estimated profit is displayed as fact.</p></section></div>}</div>;
}
