import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

interface Summary { registered_users: number; active_users: number; active_subscribers: number; standard_subscribers: number; pro_subscribers: number; premium_subscribers: number; creator_subscribers: number; generation_requests_today: number; videos_today: number; images_today: number; total_revenue: number; revenue_today: number; }
interface Economics { provider: string; model: string; requests: number; provider_cost_usd: number; credits_charged: number; revenue_usd: number; verified_provider_cost_usd: number; verified_gross_margin_usd: number; }

export function AdminOperationsPage() {
  const [summary, setSummary] = useState<Summary | null>(null); const [economics, setEconomics] = useState<Economics[]>([]); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; void (async () => { const [summaryResult, economicsResult] = await Promise.all([supabase.from("v_admin_operations_summary").select("*").single(), supabase.from("v_admin_model_economics").select("*").order("provider").order("model")]); if (!active) return; if (summaryResult.error) setError(summaryResult.error.message); else setSummary(summaryResult.data as Summary); if (!economicsResult.error) setEconomics((economicsResult.data ?? []) as Economics[]); })(); return () => { active = false; }; }, []);
  const cards = summary ? [["Registered users", summary.registered_users], ["Active users", summary.active_users], ["Active subscribers", summary.active_subscribers], ["Requests today", summary.generation_requests_today], ["Videos today", summary.videos_today], ["Images today", summary.images_today]] : [];
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold text-ink-900">Operations & Margin</h1><p className="mt-1 text-sm text-ink-500">Live operational metrics and verified provider economics.</p></div>{error && <div className="card p-4 text-sm text-rose-600">Unable to load operations summary: {error}</div>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([label, value]) => <div key={String(label)} className="card p-5"><p className="text-sm text-ink-500">{label}</p><p className="mt-2 text-2xl font-semibold text-ink-900">{Number(value).toLocaleString()}</p></div>)}</div>{summary && <section className="card p-5"><h2 className="font-semibold">Subscribers by plan</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Standard",summary.standard_subscribers],["Pro",summary.pro_subscribers],["Premium",summary.premium_subscribers],["Creator",summary.creator_subscribers]].map(([name,count]) => <div key={String(name)} className="rounded-lg bg-ink-50 p-3"><p className="text-xs text-ink-500">{name}</p><p className="mt-1 text-xl font-semibold">{Number(count).toLocaleString()}</p></div>)}</div></section>}{summary && <section className="card p-5"><h2 className="font-semibold">Revenue</h2><div className="mt-4 grid grid-cols-2 gap-4"><div><p className="text-xs text-ink-500">All-time successful</p><p className="mt-1 text-xl font-semibold">${Number(summary.total_revenue).toLocaleString()}</p></div><div><p className="text-xs text-ink-500">Today</p><p className="mt-1 text-xl font-semibold">${Number(summary.revenue_today).toLocaleString()}</p></div></div></section>}
  <section className="card overflow-hidden"><div className="border-b border-ink-200 p-5"><h2 className="font-semibold">Model economics</h2><p className="mt-1 text-xs text-ink-500">Verified margin uses only provider costs marked verified.</p></div>{economics.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-ink-50 text-xs text-ink-500"><tr><th className="px-5 py-3">Provider / model</th><th className="px-5 py-3">Requests</th><th className="px-5 py-3">Credits</th><th className="px-5 py-3">Est. cost</th><th className="px-5 py-3">Verified cost</th><th className="px-5 py-3">Verified margin</th></tr></thead><tbody className="divide-y divide-ink-100">{economics.map((row) => <tr key={`${row.provider}:${row.model}`}><td className="px-5 py-3"><div className="font-medium text-ink-900">{row.model}</div><div className="text-xs text-ink-400">{row.provider}</div></td><td className="px-5 py-3">{Number(row.requests).toLocaleString()}</td><td className="px-5 py-3">{Number(row.credits_charged).toLocaleString()}</td><td className="px-5 py-3">${Number(row.provider_cost_usd).toFixed(4)}</td><td className="px-5 py-3">${Number(row.verified_provider_cost_usd).toFixed(4)}</td><td className="px-5 py-3 font-semibold">${Number(row.verified_gross_margin_usd).toFixed(4)}</td></tr>)}</tbody></table></div> : <div className="p-5 text-sm text-ink-500">No provider cost events recorded yet. Verified margin will appear automatically after real provider charges are reconciled.</div>}</section></div>;
}
